### ISSUE TITLE
Corner is not fixed when resizing circle / ellipse

### ISSUE THREAD

**Issue by RomainCscn** [svgdotjs/svg.resize.js#41]
Hi! 

I noticed that when resizing a circle or an ellipse, the corner is not fixed and move during the resize.

Here is an example with an ellipse and a path to show the difference:

https://jsfiddle.net/2tytq49v/3/

Thank you.

**Comment by Fuzzyma** [comment]
We are aware of this problem but unfortunately there is no much we can do about that. Circles and ellipses are drawn using there center as position. However when resizing both are positioned using the upper left corner. So it can happen that this upper left edges moves around a bit because under the hood the center is changed and math does not work out at any case Espe when you resize so fast that it cannot reposition the element fast enough
